---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data(rest_inspec)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec %>% 
  filter(boro == "MANHATTAN",
         cuisine_description == "Korean") %>%
  drop_na(score) %>% 
  group_by(dba) %>% 
  summarize(score = score) %>% 
  mutate(dba = fct_reorder(dba, score)) %>% 
  plot_ly(
    x = ~ dba, y = ~ score, type = "box", colors = "viridis") %>% 
    layout(title = "Score Distribution of Korean \nRestaurant Inspections in Manhattan", 
     xaxis = list(title = "Korean Restaurant"), 
     yaxis = list(title = "Score"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec %>% 
  filter(boro != "Missing") %>% 
  group_by(grade, boro) %>% 
  summarize(n_obs = n()) %>% 
  filter(grade %in% c("A", "B", "C")) %>% 
  plot_ly(x = ~ grade, y = ~ n_obs, type = "bar", color = ~ boro) %>% 
  layout(
    title = "Restaurant Grade Distribution in New York",
    xaxis = list(title = "Restaurant Grade"), 
    yaxis = list(title = "Number of Restaurants"),
    barmode = "stack")
```

### Chart C

```{r}
rest_inspec %>% 
  filter(boro != "Missing",
         cuisine_description == "Asian") %>% 
  drop_na(score) %>% 
  group_by(boro, dba) %>% 
  summarize(score = mean(score)) %>% 
  plot_ly(
    x = ~ dba, y = ~ score, color = ~ boro, type = "scatter", mode = "markers", alpha = 0.7) %>% 
  layout(title = "Asian Restaurant Inspection \nScores",
          xaxis = list(title = "Asian Restaurants",
                      showticklabels = FALSE),
          yaxis = list(title = "Score"))
```


```{r}

```

